# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - cuculicdemo1

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  DAY_OF_WEEK: Monday

jobs:
  OkLetsBuildThisBEotch:
    runs-on: windows-latest
    
    env:
      Greeting: Hello
      
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Awwwe yeahhhh! Restorin sum Dependencies...
        run: dotnet restore

      - name: Ok, let's build this bad boy with dotnet
        run: dotnet build --configuration Release

      - name: trying something new here    
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Mona

      # Publish all the files needed to run the app to a folder.
      - name: Next up, good old dotnet publish. We're publishing to the root/myapp
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"


      # Now let's gather up those files and assign them to a vaiable, then upload them using the upload-artifact method.
      - name: Upload artifact for deployment job. This is just the website part. Not the db.
        uses: actions/upload-artifact@v4
        with:
          # name = Variable name. the name of the artifact to upload. An 'artifact' can be a single file or collection of files. 
          # this is just a variable name. It is unimportant. Call it whatever you want.
          # Optional. Default is 'artifact'
          name: AllMyDeploymentFiles
          # A single file, filepath or wildcard pattern that describes what to upload
          # in the example below, we are uploading everything in the myapp directory, which in this case is the published app that we published in the step above
          # Upload all files in the 'myapp' folder, and name that collection of stuff 'AllMyDeploymentFiles'
          path: ${{env.DOTNET_ROOT}}/myapp

      - name: Install EntityFrameworkCore Tools
        run: |
            dotnet new tool-manifest
            dotnet tool install dotnet-ef

      - name: Generate EF Core Migration Script
        run: dotnet ef migrations script --no-build --idempotent --configuration Release --output C:\Users\runneradmin\AppData\Local\Microsoft\dotnet/sql/sql-script.sql --context DeploymentApp.Data.ProjectContext --project ${{ github.workspace }}/DeploymentApp/DeploymentApp.csproj

      - uses: actions/upload-artifact@v4
        with:
          name: dll-updates
          # Path is the file or files you want to package up.
          # It could be a file path to a single file, an entire directory, or a wildcard pattern that describes what to upload
          # in the example below, we are uploading a single file, which in this case is the published app that we published in the step above
          # Upload all files in the 'myapp' folder, and name that collection of stuff 'AllMyDeploymentFiles'
          path: ${{env.DOTNET_ROOT}}/sql/sql-script.sql
          if-no-files-found: error

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job - PROD
        uses: actions/download-artifact@v4
      
      - name: Login to Azure - PROD
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EDD0E1C2EDFB4853A5C16DEBA44124A6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BE1D17F935CE4306B27E80784CFBBEBA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A3D08ED714F84FFDBE68E2E82541BCF9 }}

      - name: Deploy to Azure Web App - PROD
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cuculicdemo1'
          slot-name: 'Production'
          package: ./AllMyDeploymentFiles/

      - name: Azure SQL Deploy - PROD
        uses: Azure/sql-action@v2.3
        with:
          # The connection string, including authentication information, for the Azure SQL Server database.
          connection-string: ${{ secrets.SQL_CONNECTION_STRING }}
          # Path to the file used for this action. Supported file types are .sql, .dacpac, or .sqlproj
          path: './dll-updates/sql/sql-script.sql'
          
